name: Update Weather Data

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:     # Manual trigger support

jobs:
  update-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install python-dotenv requests

      - name: Run Weather Script
        run: python scripts/weather.py

      - name: Commit Weather JSON
        run: |
          git config --global user.name "MiniHabits Bot"
          git config --global user.email "bot@minihabits.local"
          git add weather.json
          git commit -m "🔄 Update weather data"
          git push
        env:
          WEATHERAPI_KEY: ${{ secrets.WEATHERAPI_KEY }}